spring:
  application:
    name: E-Car
  datasource:
    url: jdbc:mysql://localhost:3306/ecar
    username: root
    password: Furkan.63
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

